# Generated by Django 3.2 on 2023-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230522_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='character',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
