# Generated by Django 3.2 on 2023-05-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230524_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(blank=True, to='accounts.Genre'),
        ),
    ]
